/**
 * claimlink.ts — send a private payment as a shareable link, no recipient
 * address required.
 *
 * This is the "claim link" pattern Solana makes possible (productized by
 * TipLink): the sender mints a throwaway keypair `E`, funds it, and hands the
 * recipient a URL that carries E's secret. Whoever opens the link controls E and
 * sweeps the funds into their own wallet. The recipient never had to share an
 * address, and never needed a wallet beforehand.
 *
 * Why an ephemeral account at all: a shielded ER->ER transfer requires the
 * recipient's ATA to already be delegated (they must have "onboarded"), so you
 * cannot privately transfer to an address that has never used the app. The link
 * account sidesteps that — funds leave the sender's SHIELDED balance in one
 * `ephemeral -> base` transfer (private source, plain destination ATA), land on
 * the throwaway address, and the recipient re-shields on their side after claim.
 *
 * Privacy note: the memo and amount ride in the URL *fragment* (after `#`),
 * which browsers never transmit to servers and which stays on-device in a deep
 * link. On-chain there is only a transfer to an unlabeled throwaway address.
 */
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
} from '@solana/web3.js';
import {
  createAssociatedTokenAccountInstruction,
  createTransferInstruction,
  getAccount,
  getAssociatedTokenAddressSync,
  TokenAccountNotFoundError,
} from '@solana/spl-token';
import bs58 from 'bs58';
import Constants from 'expo-constants';
import { USDC_MINT, USDC_DECIMALS } from './constants';
import { baseConnection } from './connections';
import { buildTransfer, signAndSend } from './payments';
import { getApiToken } from './apiSession';
import { getTeeToken } from './session';
import { sendBaseTx } from './chain';
import { addLinkEntry } from './registry';
import type { Signer } from './signer';

const USDC = new PublicKey(USDC_MINT);
// The deep-link scheme is environment-specific (palm / palmdev / palmpreview),
// so read it from the resolved app config — a link generated by this build opens
// only this build, and `isClaimLink` matches the same scheme the OS delivers.
const rawScheme = Constants.expoConfig?.scheme;
const LINK_SCHEME = (Array.isArray(rawScheme) ? rawScheme[0] : rawScheme) ?? 'palm';
const LINK_HOST = 'claim';

// The throwaway account pays its own claim fee + the recipient's ATA rent, so it
// is fully self-custodial (the recipient signs nothing on-chain to claim). ~1 SPL
// ATA rent (~0.00204 SOL) + a little slack for fees.
const LINK_LAMPORTS = 3_000_000; // 0.003 SOL
// Covers the sender's own signature on the seed tx, plus slack.
const FEE_BUFFER_LAMPORTS = 15_000;

export interface ClaimLink {
  /** The full `palm://claim#...` URL to share with the recipient. */
  url: string;
  /** The throwaway account holding the funds until claimed. */
  linkAddress: string;
  /** Base units (USDC) parked on the link. */
  amount: bigint;
  memo?: string;
}

export interface ParsedClaimLink {
  keypair: Keypair;
  linkAddress: string;
  amount?: bigint;
  memo?: string;
}

function toBaseUnits(dollars: number): bigint {
  return BigInt(Math.round(dollars * 10 ** USDC_DECIMALS));
}

/** Lamports as a short SOL string, e.g. 3_005_000 -> "0.003". */
function fmtSol(lamports: number): string {
  return (lamports / LAMPORTS_PER_SOL).toFixed(4).replace(/\.?0+$/, '');
}

/**
 * Create a shareable private-payment link for `dollars`, funded from the
 * sender's SHIELDED balance. Returns the URL to hand off (e.g. via the OS share
 * sheet). Performs two sender-signed txs: seed the link account with fee SOL,
 * then move the USDC out of the private pool onto it.
 */
export async function createClaimLink(
  signer: Signer,
  dollars: number,
  memo?: string,
): Promise<ClaimLink> {
  const amount = toBaseUnits(dollars);

  // A link is funded with SOL, not just USDC: the throwaway account must carry
  // enough to pay the recipient's ATA rent and its own claim fee. Check FIRST —
  // the seed transfer below is the very first thing that touches the wallet, so
  // without this the user signs, waits, and gets an opaque System-program
  // `Custom(1)` ("insufficient lamports") back from the chain.
  const sol = await baseConnection().getBalance(signer.publicKey);
  const needed = LINK_LAMPORTS + FEE_BUFFER_LAMPORTS;
  if (sol < needed) {
    throw new Error(
      `Not enough SOL to create a link. This wallet has ${fmtSol(sol)} SOL but ` +
        `needs about ${fmtSol(needed)} — a link carries its own SOL so the ` +
        `recipient can claim without a funded wallet. Add some SOL and retry. ` +
        `(Your USDC balance is not the problem.)`,
    );
  }

  const link = Keypair.generate();

  // 1. Seed the link account with enough SOL to pay its own claim fee + the
  //    recipient's ATA rent. Sender is fee payer.
  await sendBaseTx(
    [
      SystemProgram.transfer({
        fromPubkey: signer.publicKey,
        toPubkey: link.publicKey,
        lamports: LINK_LAMPORTS,
      }),
    ],
    signer,
  );

  // 2. Move the USDC out of the sender's private balance to the link account's
  //    plain base ATA. `ephemeral -> base` needs no onboarding at the
  //    destination; `initAtasIfMissing` creates the link's ATA (sender pays).
  const [apiToken, teeToken] = await Promise.all([
    getApiToken(signer),
    getTeeToken(signer),
  ]);
  const built = await buildTransfer(
    {
      from: signer.publicKey.toBase58(),
      to: link.publicKey.toBase58(),
      amount, // bigint => passed through as base units
      visibility: 'private',
      fromBalance: 'ephemeral',
      toBalance: 'base',
    },
    apiToken,
  );
  await signAndSend(built, signer, teeToken);

  const url = encodeClaimLink(link, amount, memo);
  const linkAddress = link.publicKey.toBase58();
  // Persist BEFORE returning so the secret survives a dismissed share sheet — it
  // is the only key to the funds, and the sender can reclaim later if unclaimed.
  await addLinkEntry({
    url,
    linkAddress,
    amount: amount.toString(),
    memo,
    createdAt: Date.now(),
  });

  return { url, linkAddress, amount, memo };
}

/** Build the `palm://claim#...` URL. Secret + memo + amount live in the fragment. */
export function encodeClaimLink(
  link: Keypair,
  amount: bigint,
  memo?: string,
): string {
  const params = new URLSearchParams();
  params.set('k', bs58.encode(link.secretKey));
  params.set('a', amount.toString());
  if (memo) params.set('m', memo);
  return `${LINK_SCHEME}://${LINK_HOST}#${params.toString()}`;
}

/** True if `url` is one of our claim links (deep-link router guard). */
export function isClaimLink(url: string): boolean {
  return url.startsWith(`${LINK_SCHEME}://${LINK_HOST}`);
}

/** Parse a `palm://claim#...` URL back into the link keypair + metadata. */
export function parseClaimLink(url: string): ParsedClaimLink {
  const hash = url.indexOf('#');
  if (hash < 0) throw new Error('Not a claim link: missing key fragment.');
  const params = new URLSearchParams(url.slice(hash + 1));
  const k = params.get('k');
  if (!k) throw new Error('Not a claim link: missing key.');
  const keypair = Keypair.fromSecretKey(bs58.decode(k));
  const a = params.get('a');
  const m = params.get('m');
  return {
    keypair,
    linkAddress: keypair.publicKey.toBase58(),
    amount: a ? BigInt(a) : undefined,
    memo: m ?? undefined,
  };
}

/**
 * Claim a link's funds into `destOwner`'s account. The link account signs and
 * pays, so the recipient needs no SOL and signs nothing — they just supply the
 * address that should receive (their own wallet). Sweeps the link ATA's ACTUAL
 * balance (not the encoded amount), so a tampered/duplicated link can't overstate
 * it. Re-shielding into the recipient's private balance is a follow-up deposit.
 */
export async function claimClaimLink(
  destOwner: PublicKey,
  linkKeypair: Keypair,
): Promise<{ amount: bigint; signature: string }> {
  const conn = baseConnection();
  const linkAta = getAssociatedTokenAddressSync(USDC, linkKeypair.publicKey, true);

  let amount: bigint;
  try {
    amount = (await getAccount(conn, linkAta)).amount;
  } catch (e) {
    if (e instanceof TokenAccountNotFoundError) {
      throw new Error('This link is empty — it may have already been claimed.');
    }
    throw e;
  }
  if (amount === 0n) {
    throw new Error('This link is empty — it may have already been claimed.');
  }

  const destAta = getAssociatedTokenAddressSync(USDC, destOwner, true);
  const ixs = [];
  // Create the recipient's ATA if they've never held this mint (link pays rent).
  const destInfo = await conn.getAccountInfo(destAta);
  if (!destInfo) {
    ixs.push(
      createAssociatedTokenAccountInstruction(
        linkKeypair.publicKey, // payer (the funded link account)
        destAta,
        destOwner,
        USDC,
      ),
    );
  }
  ixs.push(
    createTransferInstruction(linkAta, destAta, linkKeypair.publicKey, amount),
  );

  const { blockhash, lastValidBlockHeight } =
    await conn.getLatestBlockhash('confirmed');
  const tx = new Transaction();
  tx.add(...ixs);
  tx.feePayer = linkKeypair.publicKey;
  tx.recentBlockhash = blockhash;
  tx.sign(linkKeypair); // fully self-custodial: only the link key signs

  const signature = await conn.sendRawTransaction(tx.serialize(), {
    skipPreflight: true,
  });
  const conf = await conn.confirmTransaction(
    { signature, blockhash, lastValidBlockHeight },
    'confirmed',
  );
  if (conf.value.err) {
    throw new Error(`Claim failed on-chain: ${JSON.stringify(conf.value.err)}`);
  }
  return { amount, signature };
}
